syntax = "proto3";

package opcomms.extcomm;

// ------------------------------ Command payload ------------------------------
message StreamCommand {
    bool streaming = 1; // true=start, false=stop
    uint32 stream_rate = 2; // desired stream rate (Hz)
}

message Command {
    uint32 packet_id = 1; // unique packet ID for acknowledgment

    oneof cmd {
        StreamCommand stream_command = 2;
    }
}

// ------------------------------ Stream payload -------------------------------
enum Axis {
    AXIS_PAN     = 0;
    AXIS_TILT    = 1;
    AXIS_UNKNOWN = 2;
}

enum MotorDirection {
    MOTOR_DIR_CW      = 0;
    MOTOR_DIR_CCW     = 1;
    MOTOR_DIR_UNKNOWN = 2;
}

message AxisInfo {
    Axis           axis      = 1;
    float          angle_deg = 2;
    MotorDirection motor_dir = 3;
    uint32         motor_pwm = 4;
}

message Stream {
    oneof data {
        AxisInfo axis_info = 1;
    }
}

// ---------------------- Package acknowledgment payload -----------------------
enum AckCode {
    STATUS_OK               = 0;
    STATUS_INVALID_DATA     = 1;
    STATUS_OPERATION_FAILED = 2;
}

message Ack {
    AckCode code = 1; // ack code
}

// ------------------- Generic external communication packet -------------------
enum SchemaVersion {
    SCHEMA_V_UNKNOWN = 0;
    SCHEMA_V1 = 1;
}

message Header {
  uint32 schema_version = 1;
  uint32 pkt_id         = 2;
}

message ExtcommPacket {
    Header header = 1;

    oneof payload {
        Command command = 2;
        Stream  stream  = 3;
        Ack     ack     = 4;
    }
}
