syntax = "proto3";

package opcomms.extcomm;

import "extcomm/common.proto";

message GimbalStatusResponse {
    // Gimbal mode
    uint32 mode = 1;

    // Soft limits (in degrees)
    float pan_lower_limit = 2;
    float pan_upper_limit = 3;

    // Current and commanded values (in degrees)
    float pan_setpoint_deg = 4;
    float pan_angle_deg = 5;

    // Whether or not the current configuration has been saved
    bool saved_configuration = 6;

    // Streaming settings
    uint32 stream_rate = 7;
    bool stream_enabled = 8;
}

message PidConfigResponse {
    float Kp = 1;
    float Ki = 2;
    float Kd = 3;
    float tau = 4;
    float outLimMin = 5;
    float outLimMax = 6;
    float intLimMin = 7;
    float intLimMax = 8;
}

message GimbalConfigurationResponse {
    uint32 serialNumber = 1;

    // Saved pan PID controller configuration
    PidConfigResponse pan_pid = 2;
}

message PanSetPosResponse {
    float setpoint = 1;
    bool accepted = 2;
    string message = 3;
}

// Response packets are server -> client packets sent in reply to a received command.
message ResponsePacket {
    Header header = 1;

    oneof payload {
        GimbalStatusResponse gimbal_status = 10;
        PidConfigResponse pan_pid_config = 20;
        GimbalConfigurationResponse gimbal_config = 30;
        PanSetPosResponse pan_setpos = 40;
    }
}
